# ============================================================
# Plot long-term comparison:
# Original TROLL code vs deep and shallow water table implementation
# ============================================================
#
# This script should be run after the script that creates the .rds files.
#
# Expected RDS files:
# - df_water_balance_annual.rds
# - df_water_balance_other_annual.rds   optional
# - df_vertical_flux_annual.rds         optional
# - df_biogeochemical_annual.rds
#
# ============================================================


# ============================================================
# 1. Load required packages
# ============================================================

library(tidyverse)
library(data.table)
library(fs)


# ============================================================
# 2. Define directories
# ============================================================

project_dir <- path_expand("~/Desktop/Postdoc_Toulouse/TROLL/TROLL_code_understanding_documenting/runs/fixed_soil_profile/sandy/")

cache_dir <- path(project_dir, "_rds")

plot_dir <- path(project_dir, "plots")
dir_create(plot_dir)


# ============================================================
# 3. Helper functions
# ============================================================

read_required_rds <- function(file_path) {
  
  if (!file_exists(file_path)) {
    stop("Required RDS file not found: ", file_path)
  }
  
  readRDS(file_path)
}

read_optional_rds <- function(file_path) {
  
  if (!file_exists(file_path)) {
    message("Optional RDS file not found: ", file_path)
    return(NULL)
  }
  
  readRDS(file_path)
}

save_plot <- function(plot_object, filename, width = 10, height = 6, dpi = 300) {
  
  print(plot_object)
  
  ggsave(
    filename = path(plot_dir, filename),
    plot = plot_object,
    width = width,
    height = height,
    dpi = dpi
  )
  
  message("Saved plot: ", path(plot_dir, filename))
}


# ============================================================
# 4. Load annual data generated by the previous script
# ============================================================

df_water_balance_annual <- read_required_rds(
  path(cache_dir, "df_water_balance_annual.rds")
)

df_biogeochemical_annual <- read_required_rds(
  path(cache_dir, "df_biogeochemical_annual.rds")
)

df_water_balance_other_annual <- read_optional_rds(
  path(cache_dir, "df_water_balance_other_annual.rds")
)

df_vertical_flux_annual <- read_optional_rds(
  path(cache_dir, "df_vertical_flux_annual.rds")
)

# ============================================================
# 4.1. Keep only the years you want to plot
# ============================================================

max_year_to_plot <- 150

keep_first_years <- function(df, max_year) {
  
  if (is.null(df)) {
    return(NULL)
  }
  
  df %>%
    filter(year <= max_year)
}

df_water_balance_annual <- keep_first_years(
  df_water_balance_annual,
  max_year_to_plot
)

df_biogeochemical_annual <- keep_first_years(
  df_biogeochemical_annual,
  max_year_to_plot
)

df_water_balance_other_annual <- keep_first_years(
  df_water_balance_other_annual,
  max_year_to_plot
)

df_vertical_flux_annual <- keep_first_years(
  df_vertical_flux_annual,
  max_year_to_plot
)

# ============================================================
# 4.2. FIX: Patch for typo in transpiration output
# ============================================================
# Problem:
# Some outputs were written as "transpitation" instead of "transpiration".
# This prevents plotting all scenarios together because the variable names
# do not match across scenarios.
#
# Solution:
# 1. Rename "transpitation" to "transpiration" wherever it appears.
# 2. If variables are stored as "transpitation_0", "transpitation_1", etc.,
#    extract the layer number and move them into the layer-level dataframe.
# 3. Do not hard-code a specific scenario, because the typo may occur in
#    Original code, Deep WT, or Shallow WT.

fix_transpiration_typo <- function(df) {
  
  if (is.null(df)) {
    return(NULL)
  }
  
  if (!"variable" %in% names(df)) {
    return(df)
  }
  
  df %>%
    mutate(
      variable = case_when(
        variable == "transpitation" ~ "transpiration",
        TRUE ~ variable
      )
    )
}


message("Checking transpiration variable names before typo patch...")

print(
  df_water_balance_annual %>%
    filter(str_detect(variable, "transp")) %>%
    count(scenario, variable)
)

if (!is.null(df_water_balance_other_annual)) {
  print(
    df_water_balance_other_annual %>%
      filter(str_detect(variable, "transp")) %>%
      count(scenario, variable)
  )
}


# ------------------------------------------------------------
# 1. Simple typo fix in the layer-level dataframe
# ------------------------------------------------------------

df_water_balance_annual <- fix_transpiration_typo(df_water_balance_annual)


# ------------------------------------------------------------
# 2. If typo variables are in the non-layer dataframe as transpitation_0,
#    transpitation_1, etc., move them to df_water_balance_annual
# ------------------------------------------------------------

if (!is.null(df_water_balance_other_annual)) {
  
  df_fixed_transpiration_from_other <- df_water_balance_other_annual %>%
    filter(str_detect(variable, "^transpitation_\\d+$")) %>%
    mutate(
      layer = as.numeric(str_extract(variable, "\\d+$")),
      variable = "transpiration"
    ) %>%
    select(any_of(names(df_water_balance_annual)))
  
  if (nrow(df_fixed_transpiration_from_other) > 0) {
    
    message("Moving transpitation_X variables from df_water_balance_other_annual to df_water_balance_annual...")
    
    df_water_balance_annual <- df_water_balance_annual %>%
      bind_rows(df_fixed_transpiration_from_other) %>%
      distinct()
  }
  
  # Clean the non-layer dataframe
  df_water_balance_other_annual <- df_water_balance_other_annual %>%
    filter(!str_detect(variable, "^transpitation_\\d+$")) %>%
    filter(variable != "transpiration1016") %>%
    mutate(
      variable = case_when(
        variable == "transpitation" ~ "transpiration",
        TRUE ~ variable
      )
    )
}


message("Checking transpiration variable names after typo patch...")

print(
  df_water_balance_annual %>%
    filter(str_detect(variable, "transp")) %>%
    count(scenario, variable, layer)
)

if (!is.null(df_water_balance_other_annual)) {
  print(
    df_water_balance_other_annual %>%
      filter(str_detect(variable, "transp")) %>%
      count(scenario, variable)
  )
}
# ============================================================
# 5. Aesthetic options
# ============================================================

# scenario_colors <- c(
#   "sandy_WTD_0_6"     = "#1B6CA8",
#   "sandy_WTD_1_6"   = "#56B4E9",
#   "sandy_WTD_1_4"   = "#CC5500",
#   "shallowWT_sandy_redprec" = "#E8A268"
# )

scenario_colors <- c(
  "sandy_WTD_0_6"     = "#1B6CA8",
  "sandy_WTD_1_6"   = "#56B4E9",
  "sandy_WTD_4"   = "#CC5500"
)


# scenario_labels <- c(
#   "deepWT_clayey_regclim"     = "Deep WT | Clayey soil | Regclim",
#   "deepWT_clayey_redprec"   = "Deep WT | Clayey soil | Redprec" ,
#   "shallowWT_sandy_regclim"   = "Shallow WT | Sandy soil | Regclim",
#   "shallowWT_sandy_redprec" = "Shallow WT | Sandy soil | Redprec"
# )

scenario_labels <- c(
  "sandy_WTD_0_6"   = "WTD 0.6 | Sandy soil | Regclim",
  "sandy_WTD_1_6"   = "WTD 1.6 | Sandy soil | Regclim",
  "sandy_WTD_4"     = "WTD 4.0| Sandy soil | Regclim"
  
)

comparison_subtitle <- " "


# ============================================================
# 6. Check available scenarios
# ============================================================

message("Scenarios in water balance annual data:")
print(unique(df_water_balance_annual$scenario))

message("Scenarios in biogeochemical annual data:")
print(unique(df_biogeochemical_annual$scenario))

if (!is.null(df_vertical_flux_annual)) {
  message("Scenarios in vertical flux annual data:")
  print(unique(df_vertical_flux_annual$scenario))
} else {
  message("No vertical flux annual data available.")
}


# ============================================================
# 7. Plot full trajectory: water balance layer variables
# ============================================================

plot_layer_variable <- function(var_name, plot_title, y_label, filename) {
  
  df_plot <- df_water_balance_annual %>%
    filter(variable == var_name) %>%
    mutate(
      layer = factor(
        layer,
        levels = sort(unique(layer))
      )
    )
  
  if (nrow(df_plot) == 0) {
    message("Variable not found in df_water_balance_annual: ", var_name)
    return(NULL)
  }
  
  p <- df_plot %>%
    ggplot(aes(
      x = year,
      y = mean_value,
      color = scenario,
      group = scenario
    )) +
    geom_line(linewidth = 0.7, alpha = 0.7) +
    facet_wrap(~ layer, scales = "free_y", labeller = labeller(layer = function(x) paste("Layer", x))) +
    scale_color_manual(
      values = scenario_colors,
      labels = scenario_labels,
      name = "Scenario"
    ) +
    guides(color = guide_legend(override.aes = list(linewidth = 2, alpha = 1))) +
    labs(
      title = plot_title,
      subtitle = comparison_subtitle,
      x = "Simulation year",
      y = y_label
    ) +
    theme_bw()+
    
    theme(
      panel.grid.minor = element_blank(),
      axis.title = element_text(size = 16), 
      axis.text = element_text(size = 14),  
      legend.title = element_text(size = 16, face = "bold"), 
      legend.text = element_text(size = 14), 
      strip.text = element_text(size = 15, face = "bold"),
      plot.title = element_text(size = 20, face = "bold"),
      plot.subtitle = element_text(size = 16),
    )
  
  save_plot(
    plot_object = p,
    filename = filename,
    width = 10,
    height = 6,
    dpi = 300
  )
  
  return(p)
}


# ------------------------------------------------------------
# SWC
# ------------------------------------------------------------

swc_full <- plot_layer_variable(
  var_name = "SWC",
  plot_title = "Annual mean soil water content by soil layer",
  y_label = "Annual mean SWC (m³/m³)",
  filename = "plot_swc.png"
)


# ------------------------------------------------------------
# SWP
# ------------------------------------------------------------

swp_full <- plot_layer_variable(
  var_name = "SWP",
  plot_title = "Annual mean soil water potential by soil layer",
  y_label = "Annual mean SWP",
  filename = "plot_swp.png"
)


# ------------------------------------------------------------
# Transpiration
# ------------------------------------------------------------

transpiration_full <- plot_layer_variable(
  var_name = "transpiration",
  plot_title = "Annual mean transpiration by soil layer",
  y_label = "Annual mean transpiration",
  filename = "plot_transpiration.png"
)


# ============================================================
# 8. Plot full trajectory: water balance non-layer variables
# ============================================================

if (!is.null(df_water_balance_other_annual)) {
  
  water_balance_other_variables <- sort(
    unique(df_water_balance_other_annual$variable)
  )
  
  message("Water balance non-layer variables:")
  print(water_balance_other_variables)
  
  plot_water_balance_other <- df_water_balance_other_annual %>%
    ggplot(aes(
      x = year,
      y = mean_value,
      color = scenario,
      group = scenario
    )) +
    # geom_ribbon(
    #   aes(
    #     ymin = mean_value - sd_value,
    #     ymax = mean_value + sd_value,
    #     fill = scenario,
    #     group = scenario
    #   ),
    #   alpha = 0.15,
    #   color = NA
    # ) +
    geom_line(linewidth = 0.7, alpha = 0.3) +
    facet_wrap(~ variable, scales = "free_y") +
    scale_color_manual(
      values = scenario_colors,
      labels = scenario_labels,
      name = "Scenario"
    ) +
    scale_fill_manual(
      values = scenario_colors,
      labels = scenario_labels,
      name = "Scenario"
    ) +
    guides(
      fill = "none"
    ) +
    labs(
      title = "Annual water balance variables",
      subtitle = paste0(comparison_subtitle, " | Shaded area = annual mean ± SD"),
      x = "Simulation year",
      y = "Annual mean value"
    ) +
    theme_bw()
  
  save_plot(
    plot_object = plot_water_balance_other,
    filename = "plot_water_balance.png",
    width = 11,
    height = 7,
    dpi = 300
  )
  
  # Save one plot per non-layer water balance variable
  walk(water_balance_other_variables, function(var_i) {
    
    p <- df_water_balance_other_annual %>%
      filter(variable == var_i) %>%
      ggplot(aes(
        x = year,
        y = mean_value,
        color = scenario,
        group = scenario
      )) +
      # geom_ribbon(
      #   aes(
      #     ymin = mean_value - sd_value,
      #     ymax = mean_value + sd_value,
      #     fill = scenario,
      #     group = scenario
      #   ),
      #   alpha = 0.15,
      #   color = NA
      # ) +
      geom_line(linewidth = 0.7, alpha = 0.3) +
      scale_color_manual(
        values = scenario_colors,
        labels = scenario_labels,
        name = "Scenario"
      ) +
      scale_fill_manual(
        values = scenario_colors,
        labels = scenario_labels,
        name = "Scenario"
      ) +
      guides(
        fill = "none"
      ) +
      labs(
        title = paste("Annual", var_i),
        subtitle = paste0(comparison_subtitle, " | Shaded area = annual mean ± SD"),
        x = "Simulation year",
        y = "Annual mean value"
      ) +
      theme_bw()
    
    filename_i <- paste0(
      "water_balance_",
      str_replace_all(var_i, "[^A-Za-z0-9_]+", "_"),
      "_full.png"
    )
    
    save_plot(
      plot_object = p,
      filename = filename_i,
      width = 8,
      height = 5,
      dpi = 300
    )
  })
  
} else {
  
  message("Skipping non-layer water balance plots because df_water_balance_other_annual is not available.")
  
}


# ============================================================
# 9. Plot vertical flux variables
# ============================================================
#
# Important:
# The original code does not have vertical_water_flux.txt.
# Therefore, these plots are diagnostics only for the modified code.
# They should not be interpreted as direct original-vs-deep comparisons.
# ============================================================

if (!is.null(df_vertical_flux_annual) && nrow(df_vertical_flux_annual) > 0) {
  
  message("Vertical flux variables:")
  print(unique(df_vertical_flux_annual$variable))
  
  message("Vertical flux interfaces:")
  print(unique(df_vertical_flux_annual$interface))
  
  
  # ------------------------------------------------------------
  # Mean harmonic hydraulic conductivity
  # ------------------------------------------------------------
  
  df_ks <- df_vertical_flux_annual %>%
    filter(variable == "mean_ks_harmonic") %>%
    mutate(
      interface = factor(
        interface,
        levels = c("0_1", "1_2", "2_3", "3_4", "4_5")
      ),
      mean_value_log = if_else(
        mean_value > 0,
        mean_value,
        NA_real_
      )
    )
  
  if (nrow(df_ks) > 0) {
    
    mean_ks_harmonic_full <- df_ks %>%
      ggplot(aes(
        x = year,
        y = mean_value_log,
        color = scenario,
        group = scenario
      )) +
      geom_line(linewidth = 0.7) +
      facet_wrap(~ interface, scales = "free_y") +
      scale_color_manual(
        values = scenario_colors,
        labels = scenario_labels,
        name = "Scenario"
      ) +
      scale_y_log10() +
      labs(
        title = "Mean harmonic hydraulic conductivity by interface",
        subtitle = "Modified code diagnostic only",
        x = "Simulation year",
        y = "Annual mean Ks harmonic"
      ) +
      theme_bw()
    
    save_plot(
      plot_object = mean_ks_harmonic_full,
      filename = "plot_mean_ks_harmonic_full.png",
      width = 10,
      height = 6,
      dpi = 300
    )
    
  } else {
    
    message("Variable mean_ks_harmonic not found in df_vertical_flux_annual.")
    
  }
  
  
  # ------------------------------------------------------------
  # Gross volumetric change
  # ------------------------------------------------------------
  
  df_gross <- df_vertical_flux_annual %>%
    filter(variable == "gross_volumetric_change") %>%
    mutate(
      interface = factor(
        interface,
        levels = c("0_1", "1_2", "2_3", "3_4", "4_5")
      )
    )
  
  if (nrow(df_gross) > 0) {
    
    gross_volumetricchange_full <- df_gross %>%
      ggplot(aes(
        x = year,
        y = sum_value,
        color = scenario,
        group = scenario
      )) +
      geom_line(linewidth = 0.7) +
      facet_wrap(~ interface, scales = "free_y") +
      scale_color_manual(
        values = scenario_colors,
        labels = scenario_labels,
        name = "Scenario"
      ) +
      labs(
        title = "Gross vertical water exchange by interface",
        subtitle = "Modified code diagnostic only | Annual sums",
        x = "Simulation year",
        y = "Annual gross volumetric change"
      ) +
      theme_bw()
    
    save_plot(
      plot_object = gross_volumetricchange_full,
      filename = "plot_gross_volumetricchange.png",
      width = 10,
      height = 6,
      dpi = 300
    )
    
  } else {
    
    message("Variable gross_volumetric_change not found in df_vertical_flux_annual.")
    
  }
  
  
  # ------------------------------------------------------------
  # Net volumetric change
  # ------------------------------------------------------------
  
  df_net <- df_vertical_flux_annual %>%
    filter(variable == "net_volumetric_change") %>%
    mutate(
      interface = factor(
        interface,
        levels = c("0_1", "1_2", "2_3", "3_4", "4_5")
      )
    )
  
  if (nrow(df_net) > 0) {
    
    net_volumetricchange_full <- df_net %>%
      ggplot(aes(
        x = year,
        y = sum_value,
        color = scenario,
        group = scenario
      )) +
      geom_hline(
        yintercept = 0,
        linetype = "dotted",
        color = "grey40"
      ) +
      geom_line(linewidth = 0.7) +
      facet_wrap(~ interface, scales = "free_y") +
      scale_color_manual(
        values = scenario_colors,
        labels = scenario_labels,
        name = "Scenario"
      ) +
      labs(
        title = "Net vertical water exchange by interface",
        subtitle = "Modified code diagnostic only | Annual sums",
        x = "Simulation year",
        y = "Annual net volumetric change"
      ) +
      theme_bw()
    
    save_plot(
      plot_object = net_volumetricchange_full,
      filename = "plot_net_volumetricchange_full.png",
      width = 10,
      height = 6,
      dpi = 300
    )
    
  } else {
    
    message("Variable net_volumetric_change not found in df_vertical_flux_annual.")
    
  }
  
  
  # ------------------------------------------------------------
  # Directionality
  # ------------------------------------------------------------
  
  required_directionality_vars <- c(
    "net_volumetric_change",
    "gross_volumetric_change"
  )
  
  if (all(required_directionality_vars %in% unique(df_vertical_flux_annual$variable))) {
    
    df_directionality_annual <- df_vertical_flux_annual %>%
      filter(variable %in% required_directionality_vars) %>%
      select(
        scenario,
        year,
        interface,
        layer_upper,
        layer_lower,
        variable,
        sum_value
      ) %>%
      pivot_wider(
        names_from = variable,
        values_from = sum_value
      ) %>%
      mutate(
        abs_net_volumetric_change = abs(net_volumetric_change),
        directionality = abs_net_volumetric_change / gross_volumetric_change,
        directionality = if_else(
          is.finite(directionality),
          directionality,
          NA_real_
        ),
        interface = factor(
          interface,
          levels = c("0_1", "1_2", "2_3", "3_4", "4_5")
        )
      )
    
    volume_directionality_full <- df_directionality_annual %>%
      ggplot(aes(
        x = year,
        y = directionality,
        color = scenario,
        group = scenario
      )) +
      geom_line(linewidth = 0.7) +
      facet_wrap(~ interface, scales = "free_y") +
      scale_color_manual(
        values = scenario_colors,
        labels = scenario_labels,
        name = "Scenario"
      ) +
      labs(
        title = "Directionality of vertical water exchange by interface",
        subtitle = "Modified code diagnostic only | |net volumetric change| / gross volumetric change",
        x = "Simulation year",
        y = "Directionality"
      ) +
      theme_bw()
    
    save_plot(
      plot_object = volume_directionality_full,
      filename = "plot_volume_directionality_full_deep_only.png",
      width = 10,
      height = 6,
      dpi = 300
    )
    
    saveRDS(
      df_directionality_annual,
      path(cache_dir, "df_directionality_annual.rds")
    )
    
  } else {
    
    message("Skipping directionality plot because required variables are missing.")
    
  }
  
} else {
  
  message("Skipping vertical flux plots because df_vertical_flux_annual is not available.")
  
}


# ============================================================
# 10. Post-spinup plots
# ============================================================

post_spinup_start <- 200

df_layers_post_spinup <- df_water_balance_annual %>%
  filter(year >= post_spinup_start)

# ============================================================
# Post-spinup function: Plot specific layer variables
# ============================================================

plot_layer_variable_post_spinup <- function(var_name, plot_title, y_label, filename, layers_to_keep = NULL) {
  
  df_plot <- df_layers_post_spinup %>%
    filter(variable == var_name)
  
  # Filter specific layers if the user provides the 'layers_to_keep' argument
  if (!is.null(layers_to_keep)) {
    df_plot <- df_plot %>% filter(layer %in% layers_to_keep)
  }
  
  df_plot <- df_plot %>%
    mutate(
      layer = factor(
        layer,
        levels = sort(unique(layer))
      )
    )
  
  if (nrow(df_plot) == 0) {
    message("Variable not found in post-spinup data: ", var_name)
    return(NULL)
  }
  
  p <- df_plot %>%
    ggplot(aes(
      x = year,
      y = mean_value,
      color = scenario,
      group = scenario
    )) +
    geom_line(linewidth = 0.7, alpha = 0.7) +
    
    # Use scales = "fixed" to share the y-axis across all panels
    facet_wrap(~ layer, scales = "fixed", labeller = labeller(layer = function(x) paste("Layer", x))) +
    
    scale_color_manual(
      values = scenario_colors,
      labels = scenario_labels,
      name = "Scenario"
    ) +
    
    # Override legend aesthetics for better visibility (thicker and solid lines)
    guides(color = guide_legend(override.aes = list(linewidth = 2, alpha = 1))) +
    
    labs(
      title = plot_title,
      subtitle = comparison_subtitle,
      x = "Simulation year",
      y = y_label
    ) +
    theme_bw() +
    
    # Theme customizations: position, gridlines, and font sizes
    theme(
      legend.position = "bottom",
      panel.grid.minor = element_blank(),
      axis.title = element_text(size = 16), 
      axis.text = element_text(size = 14),  
      legend.title = element_text(size = 16, face = "bold"), 
      legend.text = element_text(size = 14), 
      strip.text = element_text(size = 15, face = "bold"),
      plot.title = element_text(size = 20, face = "bold"),
      plot.subtitle = element_text(size = 16)
    )
  
  save_plot(
    plot_object = p,
    filename = filename,
    width = 10,  # You might want to change this to 8 or 6 if the panels look too wide
    height = 6,
    dpi = 300
  )
  
  return(p)
}


# ------------------------------------------------------------
# Post-spinup SWP (Plotting only Layers 0 and 1) # plotting layers separately because of y values magnitudes
# ------------------------------------------------------------

swp_post_spinup <- plot_layer_variable_post_spinup(
  var_name = "SWP",
  plot_title = "Annual mean SWP by soil layer (after stabilization)",
  y_label = "Annual mean SWP (MPa)", # Remember to update to the correct unit if needed
  filename = "post_spinup_swp_layer2-3-4-5.png",
  layers_to_keep = c(2, 3, 4, 5) # Argument to select only the top layers
)






# ------------------------------------------------------------
# Post-spinup SWC
# ------------------------------------------------------------

swc_post_spinup <- plot_layer_variable_post_spinup(
  var_name = "SWC",
  plot_title = "Annual mean SWC by soil layer",
  y_label = "Annual mean SWC",
  filename = "plot_swc_post_spinup.png"
)


# ------------------------------------------------------------
# Post-spinup transpiration
# ------------------------------------------------------------

transpiration_post_spinup <- plot_layer_variable_post_spinup(
  var_name = "transpiration",
  plot_title = "Annual mean transpiration by soil layer",
  y_label = "Annual mean transpiration",
  filename = "plot_transpiration_post_spinup.png"
)


# ============================================================
# 11. Biogeochemical variables
# ============================================================

plot_biogeochemical_all <- df_biogeochemical_annual %>%
  ggplot(aes(
    x = year,
    y = mean_value,
    color = scenario,
    group = scenario
  )) +
  # geom_ribbon(
  #   aes(
  #     ymin = mean_value - sd_value,
  #     ymax = mean_value + sd_value,
  #     fill = scenario,
  #     group = scenario
  #   ),
  #   alpha = 0.15,
  #   color = NA
  # ) +
  geom_line(linewidth = 0.7, alpha = 0.7) +
  facet_wrap(~ variable, scales = "free_y") +
  scale_color_manual(
    values = scenario_colors,
    labels = scenario_labels,
    name = "Scenario"
  ) +
  scale_fill_manual(
    values = scenario_colors,
    labels = scenario_labels,
    name = "Scenario"
  ) +
  guides(
    fill = "none"
  ) +
  labs(
    title = "Annual biogeochemical variables",
    subtitle = paste0(comparison_subtitle),
    x = "Simulation year",
    y = "Annual mean value"
  ) +
  theme_bw()+
  # Theme customizations: position, gridlines, and font sizes
  theme(
    legend.position = "bottom",
    panel.grid.minor = element_blank(),
    axis.title = element_text(size = 16), 
    axis.text = element_text(size = 14),  
    legend.title = element_text(size = 16, face = "bold"), 
    legend.text = element_text(size = 14), 
    strip.text = element_text(size = 15, face = "bold"),
    plot.title = element_text(size = 20, face = "bold"),
    plot.subtitle = element_text(size = 16)
  )


save_plot(
  plot_object = plot_biogeochemical_all,
  filename = "plot_biogeochemical_all_full.png",
  width = 12,
  height = 8,
  dpi = 300
)


# ------------------------------------------------------------
# Save one plot per biogeochemical variable
# ------------------------------------------------------------

biogeochemical_variables <- sort(
  unique(df_biogeochemical_annual$variable)
)

walk(biogeochemical_variables, function(var_i) {
  
  p <- df_biogeochemical_annual %>%
    filter(variable == var_i) %>%
    ggplot(aes(
      x = year,
      y = mean_value,
      color = scenario,
      group = scenario
    )) +
    # geom_ribbon(
    #   aes(
    #     ymin = mean_value - sd_value,
    #     ymax = mean_value + sd_value,
    #     fill = scenario,
    #     group = scenario
    #   ),
    #   alpha = 0.15,
    #   color = NA
    # ) +
    geom_line(linewidth = 0.7) +
    scale_color_manual(
      values = scenario_colors,
      labels = scenario_labels,
      name = "Scenario"
    ) +
    scale_fill_manual(
      values = scenario_colors,
      labels = scenario_labels,
      name = "Scenario"
    ) +
    guides(
      fill = "none"
    ) +
    labs(
      title = paste("Annual", var_i),
      subtitle = paste0(comparison_subtitle, " | Shaded area = annual mean ± SD"),
      x = "Simulation year",
      y = "Annual mean value"
    ) +
    theme_bw()
  
  filename_i <- paste0(
    "biogeochemical_",
    str_replace_all(var_i, "[^A-Za-z0-9_]+", "_"),
    "_full.png"
  )
  
  save_plot(
    plot_object = p,
    filename = filename_i,
    width = 8,
    height = 5,
    dpi = 300
  )
})


# ============================================================
# 12. Post-spinup biogeochemical variables
# ============================================================

df_biogeochemical_post_spinup <- df_biogeochemical_annual %>%
  filter(year >= post_spinup_start)

plot_biogeochemical_post_spinup <- df_biogeochemical_post_spinup %>%
  ggplot(aes(
    x = year,
    y = mean_value,
    color = scenario,
    group = scenario
  )) +
  # geom_ribbon(
  #   aes(
  #     ymin = mean_value - sd_value,
  #     ymax = mean_value + sd_value,
  #     fill = scenario,
  #     group = scenario
  #   ),
  #   alpha = 0.15,
  #   color = NA
  # ) +
  geom_line(linewidth = 0.7) +
  facet_wrap(~ variable, scales = "free_y") +
  scale_color_manual(
    values = scenario_colors,
    labels = scenario_labels,
    name = "Scenario"
  ) +
  scale_fill_manual(
    values = scenario_colors,
    labels = scenario_labels,
    name = "Scenario"
  ) +
  guides(
    fill = "none"
  ) +
  labs(
    title = "Annual biogeochemical variables",
    subtitle = paste0(
      comparison_subtitle,
      " | Post-spinup period: year >= ",
      post_spinup_start,
      " | Shaded area = annual mean ± SD"
    ),
    x = "Simulation year",
    y = "Annual mean value"
  ) +
  theme_bw()

save_plot(
  plot_object = plot_biogeochemical_post_spinup,
  filename = "plot_biogeochemical_all_post_spinup.png",
  width = 12,
  height = 8,
  dpi = 300
)


# ============================================================
# 13. Save simple post-spinup summary tables
# ============================================================

summary_biogeochemical_post_spinup <- df_biogeochemical_post_spinup %>%
  group_by(
    scenario,
    variable
  ) %>%
  summarise(
    mean_post_spinup = mean(mean_value, na.rm = TRUE),
    sd_post_spinup   = sd(mean_value, na.rm = TRUE),
    min_post_spinup  = min(mean_value, na.rm = TRUE),
    max_post_spinup  = max(mean_value, na.rm = TRUE),
    .groups = "drop"
  )

write_csv(
  summary_biogeochemical_post_spinup,
  path(cache_dir, "summary_biogeochemical_post_spinup.csv")
)


summary_water_balance_layers_post_spinup <- df_layers_post_spinup %>%
  group_by(
    scenario,
    variable,
    layer
  ) %>%
  summarise(
    mean_post_spinup = mean(mean_value, na.rm = TRUE),
    sd_post_spinup   = sd(mean_value, na.rm = TRUE),
    min_post_spinup  = min(mean_value, na.rm = TRUE),
    max_post_spinup  = max(mean_value, na.rm = TRUE),
    .groups = "drop"
  )

write_csv(
  summary_water_balance_layers_post_spinup,
  path(cache_dir, "summary_water_balance_layers_post_spinup_original_vs_deep.csv")
)


if (!is.null(df_water_balance_other_annual)) {
  
  summary_water_balance_other_post_spinup <- df_water_balance_other_annual %>%
    filter(year >= post_spinup_start) %>%
    group_by(
      scenario,
      variable
    ) %>%
    summarise(
      mean_post_spinup = mean(mean_value, na.rm = TRUE),
      sd_post_spinup   = sd(mean_value, na.rm = TRUE),
      min_post_spinup  = min(mean_value, na.rm = TRUE),
      max_post_spinup  = max(mean_value, na.rm = TRUE),
      .groups = "drop"
    )
  
  write_csv(
    summary_water_balance_other_post_spinup,
    path(cache_dir, "summary_water_balance_other_post_spinup_original_vs_deep.csv")
  )
  
}


# ============================================================
# 14. Final messages
# ============================================================

message("Finished plotting original code vs deep water table implementation.")
message("Plots saved in:")
print(plot_dir)

message("Summary tables saved in:")
print(cache_dir)

# ============================================================
# Specific Plot: SWP, Layer 1, Original Code vs Deep WT
# ============================================================

# 1. Define specific colors and labels just for this plot
specific_colors <- c(
  "longterm_origcode_sandy_regclim" = "black",
  "longterm_deep_sandy_regclim"     = "#1B6CA8"
)

specific_labels <- c(
  "longterm_origcode_sandy_regclim" = "Original code",
  "longterm_deep_sandy_regclim"     = "Deep WT"
)

# 2. Filter data for Layer 1 and the two specific scenarios
df_plot_layer1 <- df_layers_post_spinup %>%
  filter(
    variable == "SWP", # Change to "SWC" if you want Soil Water Content instead
    layer == 1,
    scenario %in% c("longterm_origcode_sandy_regclim", "longterm_deep_sandy_regclim")
  )

# 3. Create the plot (No facet_wrap needed since it's only one layer)
p_layer1 <- df_plot_layer1 %>%
  ggplot(aes(
    x = year,
    y = mean_value,
    color = scenario 
  )) +
  # Using alpha = 0.8 so the black line doesn't completely block the blue one if they overlap
  geom_line(linewidth = 0.7, alpha = 0.8) + 
  
  scale_color_manual(
    values = specific_colors,
    labels = specific_labels,
    name = "Scenario"
  ) +
  
  # Thicker lines in the legend for better visibility
  guides(color = guide_legend(override.aes = list(linewidth = 2, alpha = 1))) +
  
  labs(
    title = "Annual mean SWP - Layer 1",
    subtitle = "Original code vs Deep water table implementation | Sandy soil | Regular climate",
    x = "Simulation year",
    y = "Annual mean SWP (MPa)" # Remember to check your unit (MPa, kPa, etc.)
  ) +
  theme_bw() +
  
  # Theme and font size customizations
  theme(
    legend.position = "bottom",
    panel.grid.minor = element_blank(),
    plot.title = element_text(size = 20, face = "bold"),
    plot.subtitle = element_text(size = 16),
    axis.title = element_text(size = 16), 
    axis.text = element_text(size = 14),  
    legend.title = element_text(size = 16, face = "bold"), 
    legend.text = element_text(size = 14)
  )

# 4. Save the plot
save_plot(
  plot_object = p_layer1,
  filename = "plot_swp_layer1_orig_vs_deep.png",
  width = 10,
  height = 6,
  dpi = 300
)

# 5. Display the plot
print(p_layer1)
