suppressPackageStartupMessages({
  library(tidyverse)
  library(lubridate)
})

# =========================================================
# Script purpose
# =========================================================
# This script reads and analyzes vertical water flux diagnostics
# generated by TROLL simulations. It can be used to inspect one
# run, compare multiple runs within the same experiment branch,
# or compare runs across different branches (e.g. deep vs shallow
# water table, sandy vs clayey soil, vegetation vs no vegetation).
#
# The script:
# - locates the requested run output files,
# - reads vertical water flux diagnostic tables,
# - reshapes the data into interface-level and layer-level formats,
# - produces faceted diagnostic plots,
# - optionally saves the figures,
# - and summarizes very small or zero Ks / harmonic Ks values.
#
# This is useful for diagnosing hydraulic behavior, identifying
# possible numerical locking, and comparing how different model
# configurations affect vertical water redistribution.

# =========================================================
# 1) PATH HELPER FUNCTIONS
# =========================================================

# Build the base branch path for a given experiment setup
make_branch_path <- function(project_dir, family, vegetation, water_table, texture) {
  file.path(
    project_dir,
    "runs",
    family,
    vegetation,
    water_table,
    texture
  )
}

# Build a configuration list for a single run
make_run_config <- function(
    project_dir,
    family,
    vegetation,
    water_table,
    texture,
    experiment_name,
    out_prefix = "(null)"
) {
  branch_path <- make_branch_path(
    project_dir = project_dir,
    family = family,
    vegetation = vegetation,
    water_table = water_table,
    texture = texture
  )
  
  run_dir <- file.path(branch_path, experiment_name)
  output_dir <- file.path(run_dir, "output")
  
  list(
    branch_path = branch_path,
    run_dir = run_dir,
    output_dir = output_dir,
    flux_path = file.path(output_dir, paste0(out_prefix, "_0_vertical_water_flux.txt")),
    figure_dir = file.path(run_dir, "_plots_vertical_flux"),
    model_name = experiment_name
  )
}

# Build a dataframe for multiple runs under the same branch
make_flux_files_df <- function(
    project_dir,
    family,
    vegetation,
    water_table,
    texture,
    experiment_names,
    out_prefix = "(null)"
) {
  branch_path <- make_branch_path(
    project_dir = project_dir,
    family = family,
    vegetation = vegetation,
    water_table = water_table,
    texture = texture
  )
  
  tibble(
    model_name = experiment_names,
    run_dir = file.path(branch_path, experiment_names),
    experiment_dir = file.path(run_dir, "output"),
    flux_path = file.path(experiment_dir, paste0(out_prefix, "_0_vertical_water_flux.txt"))
  )
}

# Build a dataframe for runs that may belong to different branches
# Required columns in experiment_table:
# family, vegetation, water_table, texture, experiment_name
make_flux_files_df_from_table <- function(project_dir, experiment_table, out_prefix = "(null)") {
  required_cols <- c("family", "vegetation", "water_table", "texture", "experiment_name")
  
  missing_cols <- setdiff(required_cols, names(experiment_table))
  if (length(missing_cols) > 0) {
    stop("experiment_table is missing required column(s): ",
         paste(missing_cols, collapse = ", "))
  }
  
  experiment_table %>%
    mutate(
      branch_path = purrr::pmap_chr(
        list(family, vegetation, water_table, texture),
        ~ file.path(project_dir, "runs", ..1, ..2, ..3, ..4)
      ),
      run_dir = file.path(branch_path, experiment_name),
      experiment_dir = file.path(run_dir, "output"),
      flux_path = file.path(experiment_dir, paste0(out_prefix, "_0_vertical_water_flux.txt")),
      model_name = experiment_name
    )
}

# =========================================================
# 2) FILE READING AND CHECKS
# =========================================================

# Check whether required flux files exist
check_flux_files <- function(files_df) {
  missing_files <- files_df %>%
    filter(!file.exists(flux_path))
  
  if (nrow(missing_files) > 0) {
    stop(
      "These flux files were not found:\n",
      paste(missing_files$flux_path, collapse = "\n")
    )
  }
}

# Read a vertical water flux file and drop empty unnamed columns
read_flux_file <- function(path) {
  df <- read.table(
    path,
    header = TRUE,
    sep = "\t",
    check.names = FALSE,
    fill = TRUE
  )
  
  empty_idx <- which(names(df) == "")
  if (length(empty_idx) > 0) {
    names(df)[empty_idx] <- paste0("empty_col_", seq_along(empty_idx))
  }
  
  df %>%
    select(-starts_with("empty_col_"))
}

# =========================================================
# 3) DATA PROCESSING
# =========================================================

# Read all selected runs into one table
load_all_flux_runs <- function(files_df, start_date) {
  purrr::map_dfr(seq_len(nrow(files_df)), function(i) {
    df <- read_flux_file(files_df$flux_path[i])
    
    if (!"iter" %in% names(df)) {
      stop("Column 'iter' not found in: ", files_df$flux_path[i])
    }
    
    df %>%
      mutate(
        iter = as.numeric(iter),
        model_name = files_df$model_name[i],
        date = start_date + iter,
        sim_year = as.numeric(date - start_date) / 365
      )
  })
}

# Convert flux diagnostics to long format and identify metric/interface/layer
build_flux_long <- function(flux_all, model_levels = NULL, model_labels = NULL) {
  out <- flux_all %>%
    pivot_longer(
      cols = -c(model_name, iter, date, sim_year),
      names_to = "variable",
      values_to = "value"
    ) %>%
    mutate(
      value = as.numeric(value),
      metric = case_when(
        str_detect(variable, "^mean_flux_layers") ~ "mean_flux",
        str_detect(variable, "^mean_abs_flux_layers") ~ "mean_abs_flux",
        str_detect(variable, "^mean_delta_swp_layers") ~ "mean_delta_swp",
        
        str_detect(variable, "^mean_matric_gradient_layers") ~ "mean_matric_gradient",
        str_detect(variable, "^mean_abs_matric_gradient_layers") ~ "mean_abs_matric_gradient",
        str_detect(variable, "^mean_hydraulic_gradient_layers") ~ "mean_hydraulic_gradient",
        str_detect(variable, "^mean_abs_hydraulic_gradient_layers") ~ "mean_abs_hydraulic_gradient",
        
        str_detect(variable, "^mean_ks_harmonic_layers") ~ "mean_ks_harmonic",
        str_detect(variable, "^net_volumetric_change_layers") ~ "net_volumetric_change",
        str_detect(variable, "^gross_volumetric_change_layers") ~ "gross_volumetric_change",
        
        str_detect(variable, "^mean_swp_layer") ~ "mean_swp_layer",
        str_detect(variable, "^mean_ks_layer") ~ "mean_ks_layer",
        TRUE ~ NA_character_
  ),
      interface = str_extract(variable, "\\d+_\\d+"),
      layer = str_extract(variable, "(?<=layer)\\d+")
    )
  
  if (!is.null(model_levels)) {
    if (is.null(model_labels)) {
      out <- out %>%
        mutate(model_name = factor(model_name, levels = model_levels))
    } else {
      out <- out %>%
        mutate(model_name = factor(model_name, levels = model_levels, labels = model_labels))
    }
  }
  
  out
}

# Split long-format data into interface-level and layer-level tables
split_flux_tables <- function(flux_long) {
  df_interface <- flux_long %>%
    filter(!is.na(metric), !is.na(interface)) %>%
    mutate(interface = factor(interface, levels = unique(interface)))
  
  df_layer <- flux_long %>%
    filter(!is.na(metric), !is.na(layer)) %>%
    mutate(layer = factor(layer, levels = unique(layer)))
  
  list(
    df_interface = df_interface,
    df_layer = df_layer
  )
}

# =========================================================
# 4) PLOT FUNCTIONS
# =========================================================

# Plot interface-level variables with one facet per interface
plot_interface_faceted <- function(data, metric_name, title_txt, y_lab, add_zero = FALSE) {
  p <- ggplot(
    data %>% filter(metric == metric_name),
    aes(x = sim_year, y = value)
  ) +
    geom_line(linewidth = 0.3) +
    facet_grid(model_name ~ interface, scales = "free_y") +
    labs(
      title = title_txt,
      x = "Time [years]",
      y = y_lab
    ) +
    theme_bw() +
    theme(
      strip.text = element_text(face = "bold"),
      plot.title = element_text(face = "bold")
    )
  
  if (add_zero) {
    p <- p + geom_hline(yintercept = 0, linetype = 2)
  }
  
  p
}

# Plot layer-level variables with one facet per layer
plot_layer_faceted <- function(data, metric_name, title_txt, y_lab, add_zero = FALSE) {
  p <- ggplot(
    data %>% filter(metric == metric_name),
    aes(x = sim_year, y = value)
  ) +
    geom_line(linewidth = 0.6) +
    facet_grid(model_name ~ layer, scales = "free_y") +
    labs(
      title = title_txt,
      x = "Time [years]",
      y = y_lab
    ) +
    theme_bw() +
    theme(
      strip.text = element_text(face = "bold"),
      plot.title = element_text(face = "bold")
    )
  
  if (add_zero) {
    p <- p + geom_hline(yintercept = 0, linetype = 2)
  }
  
  p
}

# Build all main diagnostic plots
build_flux_plots <- function(df_interface, df_layer) {
  
  p_flux <- plot_interface_faceted(
    df_interface,
    metric_name = "mean_flux",
    title_txt = "Mean flux by interface",
    y_lab = "Mean flux [m s-1]",
    add_zero = TRUE
  )
  
  p_abs_flux <- plot_interface_faceted(
    df_interface,
    metric_name = "mean_abs_flux",
    title_txt = "Mean absolute flux by interface",
    y_lab = "Mean absolute flux [m s-1]"
  )
  
  p_dphi <- plot_interface_faceted(
    df_interface,
    metric_name = "mean_delta_swp",
    title_txt = "Mean delta SWP by interface",
    y_lab = "Mean delta SWP [MPa]",
    add_zero = TRUE
  )
  
  p_matric_gradient <- plot_interface_faceted(
    df_interface,
    metric_name = "mean_matric_gradient",
    title_txt = "Mean matric gradient by interface",
    y_lab = "Mean matric gradient [-]",
    add_zero = TRUE
  )
  
  p_abs_matric_gradient <- plot_interface_faceted(
    df_interface,
    metric_name = "mean_abs_matric_gradient",
    title_txt = "Mean absolute matric gradient by interface",
    y_lab = "Mean absolute matric gradient [-]"
  )
  
  p_hydraulic_gradient <- plot_interface_faceted(
    df_interface,
    metric_name = "mean_hydraulic_gradient",
    title_txt = "Mean hydraulic gradient by interface",
    y_lab = "Mean hydraulic gradient [-]",
    add_zero = TRUE
  )
  
  p_abs_hydraulic_gradient <- plot_interface_faceted(
    df_interface,
    metric_name = "mean_abs_hydraulic_gradient",
    title_txt = "Mean absolute hydraulic gradient by interface",
    y_lab = "Mean absolute hydraulic gradient [-]"
  )
  
  p_kharm <- plot_interface_faceted(
    df_interface,
    metric_name = "mean_ks_harmonic",
    title_txt = "Mean harmonic Ks by interface",
    y_lab = "Mean harmonic Ks [m s-1]"
  )
  
  p_net <- plot_interface_faceted(
    df_interface,
    metric_name = "net_volumetric_change",
    title_txt = "Net volumetric change by interface",
    y_lab = "Net volumetric change [m3]",
    add_zero = TRUE
  )
  
  p_gross <- plot_interface_faceted(
    df_interface,
    metric_name = "gross_volumetric_change",
    title_txt = "Gross volumetric change by interface",
    y_lab = "Gross volumetric change [m3]"
  )
  
  p_swp_layer <- plot_layer_faceted(
    df_layer,
    metric_name = "mean_swp_layer",
    title_txt = "Mean SWP by layer",
    y_lab = "Mean SWP [MPa]"
  )
  
  p_ks_layer <- plot_layer_faceted(
    df_layer,
    metric_name = "mean_ks_layer",
    title_txt = "Mean Ks by layer",
    y_lab = "Mean Ks [m s-1]"
  )
  
  df_panel_interface <- df_interface %>%
    filter(metric %in% c(
      "mean_flux",
      "mean_abs_flux",
      "mean_delta_swp",
      "mean_matric_gradient",
      "mean_abs_matric_gradient",
      "mean_hydraulic_gradient",
      "mean_abs_hydraulic_gradient",
      "mean_ks_harmonic",
      "net_volumetric_change",
      "gross_volumetric_change"
    )) %>%
    mutate(
      metric = factor(
        metric,
        levels = c(
          "mean_flux",
          "mean_abs_flux",
          "mean_delta_swp",
          "mean_matric_gradient",
          "mean_abs_matric_gradient",
          "mean_hydraulic_gradient",
          "mean_abs_hydraulic_gradient",
          "mean_ks_harmonic",
          "net_volumetric_change",
          "gross_volumetric_change"
        ),
        labels = c(
          "Mean flux",
          "Mean absolute flux",
          "Mean delta SWP",
          "Mean matric gradient",
          "Mean absolute matric gradient",
          "Mean hydraulic gradient",
          "Mean absolute hydraulic gradient",
          "Mean harmonic Ks",
          "Net volumetric change",
          "Gross volumetric change"
        )
      )
    )
  
  p_panel_interface <- ggplot(
    df_panel_interface,
    aes(x = sim_year, y = value)
  ) +
    geom_line(linewidth = 0.4) +
    facet_grid(metric + model_name ~ interface, scales = "free_y") +
    labs(
      title = "Vertical water flux diagnostics by configuration and interface",
      x = "Time [years]",
      y = NULL
    ) +
    theme_bw() +
    theme(
      strip.text = element_text(face = "bold", size = 8),
      plot.title = element_text(face = "bold")
    )
  
  df_panel_layer <- df_layer %>%
    filter(metric %in% c("mean_swp_layer", "mean_ks_layer")) %>%
    mutate(
      metric = factor(
        metric,
        levels = c("mean_swp_layer", "mean_ks_layer"),
        labels = c("Mean SWP", "Mean Ks")
      )
    )
  
  p_panel_layer <- ggplot(
    df_panel_layer,
    aes(x = sim_year, y = value)
  ) +
    geom_line(linewidth = 0.5) +
    facet_grid(metric + model_name ~ layer, scales = "free_y") +
    labs(
      title = "Layer-level diagnostics by configuration and layer",
      x = "Time [years]",
      y = NULL
    ) +
    theme_bw() +
    theme(
      strip.text = element_text(face = "bold", size = 8),
      plot.title = element_text(face = "bold")
    )
  
  list(
    p_flux = p_flux,
    p_abs_flux = p_abs_flux,
    p_dphi = p_dphi,
    p_matric_gradient = p_matric_gradient,
    p_abs_matric_gradient = p_abs_matric_gradient,
    p_hydraulic_gradient = p_hydraulic_gradient,
    p_abs_hydraulic_gradient = p_abs_hydraulic_gradient,
    p_kharm = p_kharm,
    p_net = p_net,
    p_gross = p_gross,
    p_swp_layer = p_swp_layer,
    p_ks_layer = p_ks_layer,
    p_panel_interface = p_panel_interface,
    p_panel_layer = p_panel_layer
  )
}
# Save all plots to disk
save_flux_plots <- function(plots, plot_dir) {
  dir.create(plot_dir, recursive = TRUE, showWarnings = FALSE)
  
  ggsave(file.path(plot_dir, "mean_flux_by_interface_faceted.png"), plots$p_flux, width = 14, height = 8, dpi = 300)
  ggsave(file.path(plot_dir, "mean_abs_flux_by_interface_faceted.png"), plots$p_abs_flux, width = 14, height = 8, dpi = 300)
  ggsave(file.path(plot_dir, "mean_delta_swp_by_interface_faceted.png"), plots$p_dphi, width = 14, height = 8, dpi = 300)
  
  ggsave(file.path(plot_dir, "mean_matric_gradient_by_interface_faceted.png"), plots$p_matric_gradient, width = 14, height = 8, dpi = 300)
  ggsave(file.path(plot_dir, "mean_abs_matric_gradient_by_interface_faceted.png"), plots$p_abs_matric_gradient, width = 14, height = 8, dpi = 300)
  ggsave(file.path(plot_dir, "mean_hydraulic_gradient_by_interface_faceted.png"), plots$p_hydraulic_gradient, width = 14, height = 8, dpi = 300)
  ggsave(file.path(plot_dir, "mean_abs_hydraulic_gradient_by_interface_faceted.png"), plots$p_abs_hydraulic_gradient, width = 14, height = 8, dpi = 300)
  
  ggsave(file.path(plot_dir, "mean_ks_harmonic_by_interface_faceted.png"), plots$p_kharm, width = 14, height = 8, dpi = 300)
  ggsave(file.path(plot_dir, "net_volumetric_change_by_interface_faceted.png"), plots$p_net, width = 14, height = 8, dpi = 300)
  ggsave(file.path(plot_dir, "gross_volumetric_change_by_interface_faceted.png"), plots$p_gross, width = 14, height = 8, dpi = 300)
  
  ggsave(file.path(plot_dir, "mean_swp_by_layer_faceted.png"), plots$p_swp_layer, width = 14, height = 8, dpi = 300)
  ggsave(file.path(plot_dir, "mean_ks_by_layer_faceted.png"), plots$p_ks_layer, width = 14, height = 8, dpi = 300)
  
  ggsave(file.path(plot_dir, "vertical_water_flux_panel_interface_faceted.png"), plots$p_panel_interface, width = 18, height = 20, dpi = 300)
  ggsave(file.path(plot_dir, "vertical_water_flux_panel_layer_faceted.png"), plots$p_panel_layer, width = 16, height = 8, dpi = 300)
  
  cat("Saved plots in:\n", plot_dir, "\n")
}
# Print all plots
print_flux_plots <- function(plots) {
  print(plots$p_flux)
  print(plots$p_abs_flux)
  print(plots$p_dphi)
  print(plots$p_matric_gradient)
  print(plots$p_abs_matric_gradient)
  print(plots$p_hydraulic_gradient)
  print(plots$p_abs_hydraulic_gradient)
  print(plots$p_kharm)
  print(plots$p_net)
  print(plots$p_gross)
  print(plots$p_swp_layer)
  print(plots$p_ks_layer)
  print(plots$p_panel_interface)
  print(plots$p_panel_layer)
}
# =========================================================
# 5) DIAGNOSTIC SUMMARY FUNCTIONS
# =========================================================

# Summarize very small or zero mean_ks_layer values
summarize_ks_layers <- function(df_layer) {
  ks_vars <- c(
    "mean_ks_layer0",
    "mean_ks_layer1",
    "mean_ks_layer2",
    "mean_ks_layer3",
    "mean_ks_layer4",
    "mean_ks_layer5"
  )
  
  by_variable <- df_layer %>%
    filter(variable %in% ks_vars) %>%
    group_by(model_name, variable) %>%
    summarise(
      n_total = n(),
      n_non_na = sum(!is.na(value)),
      n_zero_exact = sum(value == 0, na.rm = TRUE),
      pct_zero_exact = 100 * n_zero_exact / n_total,
      n_negative = sum(value < 0, na.rm = TRUE),
      n_na = sum(is.na(value)),
      min_val = if (all(is.na(value))) NA_real_ else min(value, na.rm = TRUE),
      max_val = if (all(is.na(value))) NA_real_ else max(value, na.rm = TRUE),
      min_positive = {
        x <- value[value > 0 & !is.na(value)]
        if (length(x) == 0) NA_real_ else min(x)
      },
      n_lt_1e20 = sum(value > 0 & value < 1e-20, na.rm = TRUE),
      n_lt_1e15 = sum(value > 0 & value < 1e-15, na.rm = TRUE),
      n_lt_1e12 = sum(value > 0 & value < 1e-12, na.rm = TRUE),
      n_lt_1e10 = sum(value > 0 & value < 1e-10, na.rm = TRUE),
      n_lt_1e8  = sum(value > 0 & value < 1e-8,  na.rm = TRUE),
      .groups = "drop"
    ) %>%
    arrange(variable, model_name)
  
  all_layers <- df_layer %>%
    filter(variable %in% ks_vars) %>%
    group_by(model_name) %>%
    summarise(
      min_value_all_layers = min(value, na.rm = TRUE),
      n_zero_exact_all_layers = sum(value == 0, na.rm = TRUE),
      min_positive_all_layers = min(value[value > 0], na.rm = TRUE),
      .groups = "drop"
    )
  
  list(
    by_variable = by_variable,
    all_layers = all_layers
  )
}

# Summarize very small or zero mean_ks_harmonic values
summarize_ksh_interfaces <- function(df_interface) {
  ksh_vars <- c(
    "mean_ks_harmonic_layers0_1",
    "mean_ks_harmonic_layers1_2",
    "mean_ks_harmonic_layers2_3",
    "mean_ks_harmonic_layers3_4",
    "mean_ks_harmonic_layers4_5"
  )
  
  all_interfaces <- df_interface %>%
    filter(variable %in% ksh_vars) %>%
    group_by(model_name) %>%
    summarise(
      min_value_all_interfaces = min(value, na.rm = TRUE),
      n_zero_exact_all_interfaces = sum(value == 0, na.rm = TRUE),
      min_positive_all_interfaces = min(value[value > 0], na.rm = TRUE),
      .groups = "drop"
    )
  
  by_interface <- df_interface %>%
    filter(variable %in% ksh_vars) %>%
    mutate(interface_id = str_extract(variable, "\\d_\\d$")) %>%
    group_by(model_name, interface_id, variable) %>%
    summarise(
      n_total = n(),
      n_non_na = sum(!is.na(value)),
      n_zero_exact = sum(value == 0, na.rm = TRUE),
      pct_zero_exact = 100 * n_zero_exact / n_total,
      n_negative = sum(value < 0, na.rm = TRUE),
      n_na = sum(is.na(value)),
      min_val = if (all(is.na(value))) NA_real_ else min(value, na.rm = TRUE),
      max_val = if (all(is.na(value))) NA_real_ else max(value, na.rm = TRUE),
      min_positive = {
        x <- value[value > 0 & !is.na(value)]
        if (length(x) == 0) NA_real_ else min(x)
      },
      n_lt_1e20 = sum(value > 0 & value < 1e-20, na.rm = TRUE),
      n_lt_1e15 = sum(value > 0 & value < 1e-15, na.rm = TRUE),
      n_lt_1e12 = sum(value > 0 & value < 1e-12, na.rm = TRUE),
      n_lt_1e10 = sum(value > 0 & value < 1e-10, na.rm = TRUE),
      n_lt_1e8  = sum(value > 0 & value < 1e-8,  na.rm = TRUE),
      .groups = "drop"
    ) %>%
    arrange(interface_id, model_name)
  
  smallest_values <- df_interface %>%
    filter(variable %in% ksh_vars) %>%
    arrange(value) %>%
    select(model_name, date, variable, interface, value)
  
  list(
    all_interfaces = all_interfaces,
    by_interface = by_interface,
    smallest_values = smallest_values
  )
}

# Diagnose what happens when harmonic Ks reaches its minimum
diagnose_ksh_floor <- function(df_interface) {
  interfaces <- c("0_1", "1_2", "2_3", "3_4", "4_5")
  
  purrr::map_dfr(interfaces, function(intf) {
    ksh_var  <- paste0("mean_ks_harmonic_layers", intf)
    flux_var <- paste0("mean_abs_flux_layers", intf)
    swp_var  <- paste0("mean_delta_swp_layers", intf)
    
    ksh <- df_interface %>%
      filter(variable == ksh_var) %>%
      select(model_name, date, interface, ksh = value)
    
    flux <- df_interface %>%
      filter(variable == flux_var) %>%
      select(model_name, date, abs_flux = value)
    
    swp <- df_interface %>%
      filter(variable == swp_var) %>%
      select(model_name, date, delta_swp = value)
    
    joined <- ksh %>%
      left_join(flux, by = c("model_name", "date")) %>%
      left_join(swp, by = c("model_name", "date"))
    
    joined %>%
      group_by(model_name, interface) %>%
      summarise(
        min_ksh = min(ksh, na.rm = TRUE),
        n_at_floor = sum(ksh == min(ksh, na.rm = TRUE), na.rm = TRUE),
        mean_abs_flux_at_floor = mean(abs_flux[ksh == min(ksh, na.rm = TRUE)], na.rm = TRUE),
        median_abs_flux_at_floor = median(abs_flux[ksh == min(ksh, na.rm = TRUE)], na.rm = TRUE),
        mean_delta_swp_at_floor = mean(delta_swp[ksh == min(ksh, na.rm = TRUE)], na.rm = TRUE),
        median_delta_swp_at_floor = median(delta_swp[ksh == min(ksh, na.rm = TRUE)], na.rm = TRUE),
        .groups = "drop"
      )
  })
}

diagnose_hydraulic_locking <- function(df_interface) {
  
  interfaces <- sort(unique(na.omit(as.character(df_interface$interface))))
  
  purrr::map_dfr(interfaces, function(intf) {
    
    vars <- tibble(
      variable = c(
        paste0("mean_ks_harmonic_layers", intf),
        paste0("mean_abs_hydraulic_gradient_layers", intf),
        paste0("mean_abs_flux_layers", intf),
        paste0("gross_volumetric_change_layers", intf),
        paste0("mean_delta_swp_layers", intf)
      ),
      var_name = c(
        "ks_harmonic",
        "abs_hydraulic_gradient",
        "abs_flux",
        "gross_volumetric_change",
        "delta_swp"
      )
    )
    
    df_interface %>%
      filter(variable %in% vars$variable) %>%
      left_join(vars, by = "variable") %>%
      select(model_name, date, sim_year, interface, var_name, value) %>%
      pivot_wider(names_from = var_name, values_from = value) %>%
      group_by(model_name, interface) %>%
      summarise(
        median_ks_harmonic = median(ks_harmonic, na.rm = TRUE),
        min_ks_harmonic = min(ks_harmonic, na.rm = TRUE),
        median_abs_hydraulic_gradient = median(abs_hydraulic_gradient, na.rm = TRUE),
        median_abs_flux = median(abs_flux, na.rm = TRUE),
        median_gross_volumetric_change = median(gross_volumetric_change, na.rm = TRUE),
        median_delta_swp = median(delta_swp, na.rm = TRUE),
        
        frac_ksh_lt_1e10 = mean(ks_harmonic < 1e-10, na.rm = TRUE),
        frac_ksh_lt_1e8 = mean(ks_harmonic < 1e-8, na.rm = TRUE),
        frac_abs_gradient_lt_001 = mean(abs_hydraulic_gradient < 0.01, na.rm = TRUE),
        frac_abs_flux_lt_1e12 = mean(abs_flux < 1e-12, na.rm = TRUE),
        
        .groups = "drop"
      )
  })
}
# =========================================================
# 6) MAIN FUNCTION: SAME BRANCH
# =========================================================

# Analyze one or multiple flux runs that belong to the same branch
analyze_vertical_flux_runs <- function(
    project_dir,
    family,
    vegetation = c("veg", "noveg"),
    water_table = c("deepWT", "shallowWT"),
    texture = c("sandy", "clayey"),
    experiment_names,
    mode = 0,                  # 0 = single run, 1 = multiple runs in same branch
    save_plots = FALSE,
    start_date = as.Date("2004-01-01"),
    out_prefix = "(null)",
    model_levels = NULL,
    model_labels = NULL
) {
  vegetation <- match.arg(vegetation)
  water_table <- match.arg(water_table)
  texture <- match.arg(texture)
  
  if (!mode %in% c(0, 1)) {
    stop("'mode' must be 0 or 1.")
  }
  
  if (mode == 0 && length(experiment_names) != 1) {
    stop("For mode = 0, provide exactly one experiment name.")
  }
  
  if (mode == 1 && length(experiment_names) < 2) {
    stop("For mode = 1, provide at least two experiment names.")
  }
  
  if (mode == 0) {
    cfg <- make_run_config(
      project_dir = project_dir,
      family = family,
      vegetation = vegetation,
      water_table = water_table,
      texture = texture,
      experiment_name = experiment_names,
      out_prefix = out_prefix
    )
    
    files_df <- tibble(
      model_name = cfg$model_name,
      run_dir = cfg$run_dir,
      experiment_dir = cfg$output_dir,
      flux_path = cfg$flux_path
    )
    
    plot_dir <- cfg$figure_dir
    
  } else {
    files_df <- make_flux_files_df(
      project_dir = project_dir,
      family = family,
      vegetation = vegetation,
      water_table = water_table,
      texture = texture,
      experiment_names = experiment_names,
      out_prefix = out_prefix
    )
    
    plot_dir <- file.path(
      make_branch_path(project_dir, family, vegetation, water_table, texture),
      "_plots_vertical_flux_compare"
    )
  }
  
  check_flux_files(files_df)
  
  flux_all <- load_all_flux_runs(files_df, start_date = start_date)
  
  flux_long <- build_flux_long(
    flux_all,
    model_levels = model_levels,
    model_labels = model_labels
  )
  
  split_tables <- split_flux_tables(flux_long)
  df_interface <- split_tables$df_interface
  df_layer <- split_tables$df_layer
  
  plots <- build_flux_plots(df_interface, df_layer)
  print_flux_plots(plots)
  
  if (save_plots) {
    save_flux_plots(plots, plot_dir)
  }
  
  ks_summary <- summarize_ks_layers(df_layer)
  ksh_summary <- summarize_ksh_interfaces(df_interface)
  ksh_floor_diag <- diagnose_ksh_floor(df_interface)
  hydraulic_locking_diag <- diagnose_hydraulic_locking(df_interface)
  invisible(list(
    files_df = files_df,
    flux_all = flux_all,
    flux_long = flux_long,
    df_interface = df_interface,
    df_layer = df_layer,
    plots = plots,
    plot_dir = plot_dir,
    ks_summary = ks_summary,
    ksh_summary = ksh_summary,
    ksh_floor_diag = ksh_floor_diag,
    hydraulic_locking_diag = hydraulic_locking_diag
  ))
}

# =========================================================
# 7) MAIN FUNCTION: MIXED BRANCHES
# =========================================================

# Analyze flux runs that may belong to different branches
# experiment_table must contain:
# family, vegetation, water_table, texture, experiment_name
analyze_vertical_flux_runs_table <- function(
    project_dir,
    experiment_table,
    save_plots = FALSE,
    start_date = as.Date("2004-01-01"),
    out_prefix = "(null)",
    model_levels = NULL,
    model_labels = NULL,
    plot_dir = NULL
) {
  files_df <- make_flux_files_df_from_table(
    project_dir = project_dir,
    experiment_table = experiment_table,
    out_prefix = out_prefix
  )
  
  check_flux_files(files_df)
  
  flux_all <- load_all_flux_runs(files_df, start_date = start_date)
  
  flux_long <- build_flux_long(
    flux_all,
    model_levels = model_levels,
    model_labels = model_labels
  )
  
  split_tables <- split_flux_tables(flux_long)
  df_interface <- split_tables$df_interface
  df_layer <- split_tables$df_layer
  
  plots <- build_flux_plots(df_interface, df_layer)
  print_flux_plots(plots)
  
  if (save_plots) {
    if (is.null(plot_dir)) {
      plot_dir <- file.path(project_dir, "runs", "_plots_vertical_flux_compare")
    }
    save_flux_plots(plots, plot_dir)
  }
  
  ks_summary <- summarize_ks_layers(df_layer)
  ksh_summary <- summarize_ksh_interfaces(df_interface)
  ksh_floor_diag <- diagnose_ksh_floor(df_interface)
  hydraulic_locking_diag <- diagnose_hydraulic_locking(df_interface)
  
  invisible(list(
    files_df = files_df,
    flux_all = flux_all,
    flux_long = flux_long,
    df_interface = df_interface,
    df_layer = df_layer,
    plots = plots,
    plot_dir = plot_dir,
    ks_summary = ks_summary,
    ksh_summary = ksh_summary,
    ksh_floor_diag = ksh_floor_diag,
    hydraulic_locking_diag <- hydraulic_locking_diag
    
  ))
}

#single run
project_dir <- "/Users/biancarius/Desktop/Postdoc_Toulouse/Postdoc_Toulouse/TROLL/TROLL_code_understanding_documenting"
# 
# res1 <- analyze_vertical_flux_runs(
#   project_dir = project_dir,
#   family = "units_vertmov",
#   vegetation = "veg",
#   water_table = "deepWT",
#   texture = "sandy",
#   experiment_names = "debug_hydraulic_locking",
#   mode = 0,
#   save_plots = FALSE
# )

# #Example 2: multiple runs in the same branch
# res2 <- analyze_vertical_flux_runs(
#   project_dir = project_dir,
#   family = "theta_w_tests",
#   vegetation = "veg",
#   water_table = "deepWT",
#   texture = "sandy",
#   experiment_names = c(
#     "theta1e-3_ksfloor1e-10_veg_redprec_deepwt_sandy",
#     "theta1e-3_ksfloor1e-10_veg_redprec_deepwt_sandy"
#   ),
#   mode = 1,
#   save_plots = FALSE
# )

# experiment_table <- tibble(
#   family = c("infiltration", "infiltration", "infiltration", "infiltration", "infiltration", "infiltration", "infiltration", "infiltration"),
#   vegetation = c("veg", "veg", "veg", "veg", "veg", "veg", "veg", "veg" ),
#   water_table = c("shallowWT", "shallowWT", "deepWT", "deepWT", "shallowWT", "shallowWT", "deepWT", "deepWT"),
#   texture = c("sandy", "clayey", "sandy",  "clayey", "sandy", "clayey", "sandy",  "clayey"),
#   experiment_name = c(
#     "inf_shallowWT_sandy_regclim",
#     "inf_shallowWT_clayey_regclim",
#     "inf_deepWT_sandy_regclim",
#     "inf_deepWT_clayey_regclim",
#     "inf_shallowWT_sandy_redprec",
#     "inf_shallowWT_clayey_redprec",
#     "inf_deepWT_sandy_redprec",
#     "inf_deepWT_clayey_redprec"
#   )
# )

experiment_table <- tibble(
  family = c("infiltration"),
  vegetation = c("veg"),
  water_table = c("deepWT"),
  texture = c("sandy"),
  experiment_name = c(
    "inf_deepWT_sandy_redprec_lowertheta_longterm"
  )
)


res3 <- analyze_vertical_flux_runs_table(
  project_dir = project_dir,
  experiment_table = experiment_table,
  save_plots = FALSE
)
